aws-samples/amazon-chime-sdk

apps/moderated-chat-and-sentiment-analysis/src/Chat.jsx
apps/moderated-chat-and-sentiment-analysis/src/Config.js
apps/moderated-chat-and-sentiment-analysis/src/api/ChimeAPI.js
apps/moderated-chat-and-sentiment-analysis/src/components/Authenticated/index.jsx
apps/moderated-chat-and-sentiment-analysis/src/components/Input/index.jsx
apps/moderated-chat-and-sentiment-analysis/src/components/Messages/index.jsx
apps/moderated-chat-and-sentiment-analysis/src/components/Notifications/index.jsx
apps/moderated-chat-and-sentiment-analysis/src/components/SentimentAnalysis/index.jsx
apps/moderated-chat-and-sentiment-analysis/src/components/SentimentReaction/index.jsx
apps/moderated-chat-and-sentiment-analysis/src/constants/routes.jsx
apps/moderated-chat-and-sentiment-analysis/src/index.js
apps/moderated-chat-and-sentiment-analysis/src/providers/AuthProvider.jsx
apps/moderated-chat-and-sentiment-analysis/src/providers/ChatMessagesProvider.jsx
apps/moderated-chat-and-sentiment-analysis/src/services/MessagingService.js
apps/moderated-chat-and-sentiment-analysis/src/utilities/getReactionEmoji.jsx
apps/moderated-chat-and-sentiment-analysis/src/utilities/insertDateHeaders.jsx
apps/moderated-chat-and-sentiment-analysis/src/views/Channel/index.jsx
apps/moderated-chat-and-sentiment-analysis/src/views/JoinChannel/index.jsx

Update all copyright headers in the moderated chat and sentiment analysis to the correct copyright header 

[Moderated Chat And Sentiment Analysis] Update copyright headers

---

apps/iOS-WKWebView-sample/WkWebView Demo/HomeViewController.swift

**Issue #:**
Minor change to allow XCUITest to execute. 
**Testing**
Ran locally
Yes, this test is run on the WKWEbview demo

Minor update to iOS XCUITest

---

README.md

**Issue #:**
- Fix README chat link
**Testing**
1. How did you test these changes? Copied the link from github directly.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? NA.

Fix README chat link

---

utils/singlejs/package-lock.json

Update `ua-parser-js` from `0.7.22` to `0.7.28` and also update the package-lock to v2.
**Testing**
1. How did you test these changes? npm install && npm run bundle
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? N/A

Update ua-parser-js deps

---

apps/AmplifyDemo/src/components/Meeting.tsx

**Issue #:**
Minor bug fix.
**Testing**
Run the demo without issues
yes, with amplify demo

Minor bug fix

---

apps/chat/README.md

**Issue #:**
N/A
- Update the Chime SDK chat demo.
**Testing**
1. How did you test these changes? N/A
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? N/A

Update the Chime SDK chat demo README.md

---

README.md

**Issue #:**
The Android WebView sample demo was not listed in the main readme
Added Android WebView sample to the main readme
**Testing**
No testing was done, as it's a minor readme change
No

Added Android WebView sample to the main readme

---

apps/meeting/README.MD

**Issue #:**N/A
We launched a new feature - Amazon Voice Focus in the recent release of [React component library](https://www.npmjs.com/package/amazon-chime-sdk-component-library-react) and incorporate this feature in the meeting demo. Update the readme to add more details about the device requirement of Amazon Voice Focus.
**Testing**
1. How did you test these changes? N/A
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? N/A

Add details of device requirements in readme

---

apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/src/app.tsx
apps/meeting/src/containers/MeetingEventObserver/index.tsx

**Issue #:**
- Add meeting events component released in component library to console log meeting events through meeting lifecycle when received.
- Bump the component library version.
**Testing**
- Run the react meeting demo.
- Join the meeting, you should see meeting events logged in the console.
The react meeting demo app.

Update component library version and add meeting events

---

apps/meeting/tsconfig.json
apps/meeting/typings/amazon-chime-sdk-component-library-react.d.ts

Reverts aws-samples/amazon-chime-sdk#76

Revert "Add react component library declaration"

---

README.md
apps/chat-android/README.md
apps/chat-android/build.gradle
apps/chat-ios/Podfile
apps/chat-ios/README.md

* Update Android Build Tools version to be compatible with Android Studio 4.0 and later as stated in blog post.
* Update README
**Testing**
Running apps against iOS and android devices. 
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes

Update chat mobile demos on android build tools version and READMEs 

---

apps/meeting/src/utils/api.ts

**Issue #:**
Use `new URLSearchParams(params)` instead of "hard-coded" query parameters in `api.ts` to improve readability.
**Testing**
Run the meeting demo and make sure the updated `joinMeeting`, `endMeeting`, `getAttendee` API work well like before.
meeting demo.

Improve code style of api.ts file

---

apps/meeting/src/containers/Navigation/index.tsx

**Issue #:**
Fix the display bug of the Zoom In and Zoom Out labels.
**Testing**
Run the demo and confirm the fix works.
meeting demo.

Fix the display bug of zoom in/zoom out label

---

apps/meeting/package-lock.json
apps/meeting/package.json

**Issue #:**
- Update the meeting-dev branch to use latest released react component library.
- This is a PR after merge will merge the meeting-dev into main branch.
**Testing**
1. How did you test these changes? Tested running the demo from meeting-dev branch.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? apps/meeting

Update react component library to latest released version

---

apps/meeting/server.js

Fix Error: Cannot find module 'uuid/v4'
OS: Windows 10
npm: 7.21.1
node: 12.13.1
Description of changes:
change syntax.

Fix Error: Cannot find module 'uuid/v4

---

apps/moderated-chat-and-sentiment-analysis/package-lock.json
apps/moderated-chat-and-sentiment-analysis/package.json

**Issue #:**
moderated-chat-and-sentiment-analysis had security vulnerabilities 
Updated vulnerable packages to new versions
**Testing**
Followed README, created a CloudFormation based off the given template and tested the demo using npm run start. Works as expected. Joined with 2 attendees and sent messages which could be seen by both users.
moderated-chat-and-sentiment-analysis

[moderated-chat-and-sentiment-analysis] security alert fix

---

apps/meeting/package-lock.json
apps/meeting/package.json

Version bump for 2.13.0

---

apps/amplify-demo/package-lock.json
apps/chat/package-lock.json
apps/chat/package.json

**Issue #:**
Update sec deps.
**Testing**
Ran the demo successfully - did sanity checks. (authenticate, start channel, send message)
Yes, the chat demo was sanity tested 

Update chat demo dependencies to resolve security deps

---

apps/meeting/.eslintrc.json

Specify root in eslint config (#134)

---

apps/meeting/.eslintrc.json
apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/src/components/DeviceSelection/CameraDevices/VideoTransformDropdown.tsx
apps/meeting/src/components/DeviceSelection/CameraDevices/index.tsx
apps/meeting/src/components/MeetingControls/VideoInputTransformControl.tsx
apps/meeting/src/containers/MeetingControls/index.tsx
apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/containers/MeetingProviderWrapper/index.tsx
apps/meeting/src/providers/AppStateProvider.tsx
apps/meeting/src/types/index.ts
apps/meeting/src/utils/device-utils.ts
apps/meeting/src/utils/use-memo-compare.ts

Merging `meeting-dev` branch into `main`

---

apps/meeting/serverless/deploy.js
apps/meeting/serverless/src/package-lock.json
apps/meeting/serverless/src/package.json

**Issue #:**
add awssdk serverless package
**Testing**

awssdk serverless package

---

.gitignore
apps/chat/src/api/ChimeAPI.js
apps/chat/src/backend/serverless/template.yaml
apps/chat/src/components/ChannelModals/SetCustomStatusModal.css
apps/chat/src/components/ChannelModals/SetCustomStatusModal.jsx
apps/chat/src/components/ChannelModals/index.jsx
apps/chat/src/containers/Presence/ChannelPresence.css
apps/chat/src/containers/Presence/ChannelPresence.jsx
apps/chat/src/containers/channels/ChannelsWrapper.css
apps/chat/src/containers/channels/ChannelsWrapper.jsx
apps/chat/src/containers/channels/ModalManager.jsx
apps/chat/src/containers/input/Input.jsx
apps/chat/src/providers/AuthProvider.jsx
apps/chat/src/providers/ChatMessagesProvider/index.jsx
apps/chat/src/utilities/presence.js
apps/chat/src/views/Channels/index.jsx
apps/chat/src/views/Channels/style.css

**Issue #:** new demo
Presence demo changes
* Add channel presence feature to chat demo app
* Serverless infra changes to introduce presence feature to the chat demo app
**Testing**
tested the new demo changes with the existing chat sdk demo app features 
chat sdk demo app (channel flows demo, meetings integration demo) 

Presence demo changes

---

apps/chat/src/containers/TypingIndicator/index.css
apps/chat/src/containers/TypingIndicator/index.tsx
apps/chat/src/containers/input/Input.jsx
apps/chat/src/providers/ChatMessagesProvider/index.jsx
apps/chat/src/views/Channels/index.jsx

**Issue #:**
Typing Indicator demo
* Add typing indicator for channels
* minor fix related to presence demo to publish offline status when user logs out
**Testing**
tested the feature with existing chat sdk demo app features.
yes. chat sdk demo app (channel flows demo, meetings integration demo)

Typing Indicator demo changes

---

apps/chat/src/backend/serverless/template.yaml

**Issue #:** fix bug in the cfn template
**Testing**
tested the cfn template to create the resources
chat demo app

fix s3 bucket name for presence lambda code

---

utils/pstn-audio-lambdas/amazon-chime-pstn-audio-lambda-node/app.js

fix: correct Hangup

---

.github/PULL_REQUEST_TEMPLATE.md
apps/meeting/.eslintrc.json
apps/meeting/src/containers/Chat/ChatInput.tsx
apps/meeting/src/containers/Chat/Styled.tsx
apps/meeting/src/containers/Navigation/NavigationControl.tsx
apps/meeting/src/providers/DataMessagesProvider/index.tsx
apps/meeting/src/providers/DataMessagesProvider/state.tsx
apps/meeting/src/providers/VideoTileGridProvider/Utils.ts
apps/meeting/src/providers/VideoTileGridProvider/state.tsx
apps/meeting/src/utils/use-memo-compare.ts

**Issue #:**
- Missed running `npm run build` before running `npm run start`
as we have to do it explicitly in demo.
- Run linter and fix all warnings and errors.
- Update PR questions template to ask for `npm run build` success if applicable.
- Fix growing height when both roster and chat is shown.
**Testing**
- Running demo locally.
- Tested by deploying the demo to AWS account and if all works as expected.
- apps/meeting

Fix linting errors and warning in meeting demo

---

apps/meeting/src/components/DeviceSelection/CameraDevices/VideoTransformDropdown.tsx
apps/meeting/src/components/MeetingControls/VideoInputTransformControl.tsx
apps/meeting/src/containers/DevicePermissionPrompt.tsx
apps/meeting/src/containers/DynamicMeetingControls/index.tsx

**Issue #:**
Update video input controls and rename device permission status
**Testing**
Yes, tested in meeting demo and confirmed it works well.
Yes, meeting demo.
Yes

Update video input controls and rename device permission status

---

apps/chat/README.md

**Issue #:** presence and typing indicator demo
update readme to include presence demo blogpost link
**Testing**
N/A

update readme to include presence demo blogpost link

---

apps/chat/README.md

**Issue #:**
Minor documentation update
**Testing**
Followed directions and got demo working
yes

Minor documentation fix on chat readme prerequisite for SAM

---

apps/chat/src/containers/channels/ChannelsWrapper.jsx

**Issue #:**
Fix start and join meeting issue
**Testing**
1. How did you test these changes? Running locally 
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? chat

Fix start and join meeting bug

---

utils/singlejs/README.md
utils/singlejs/package-lock.json
utils/singlejs/package.json
utils/singlejs/rollup.config.js

**Issue #:**
Fix security vulnerability for `terser`.
- `npm audit fix` to fix `terser`.
- Upgrade to JS SDK latest v2.
Could not upgrade to V3 JS SDK due to various errors while rollup bundling. Prioritize security alert fixing for now.
**Testing**
- `npm install`
- `npm run bundle`
- Created a test.html page with below details:
```html
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
<script src="./build/amazon-chime-sdk.min.js"></script>
<script src="./build/amazon-chime-sdk.min.js.map"></script>
</head>
<body>
<script>
const logger = new …
```

Fix security vulnerability for `terser`

---

apps/meeting/package-lock.json
apps/meeting/package.json

**Issue #:**
Updated the react library to 3.5.0 and JS SDK to 3.10.0.
**Testing**
QA manual verification, regression tests.
yes
yes

Update Component Library to 3.5.0 and JS SDK to 3.10.0

---

lambda/call-insights-parsing/README.md
lambda/call-insights-parsing/docker/Dockerfile
lambda/call-insights-parsing/docker/app.py
lambda/call-insights-parsing/docker/requirements.txt

Adds sample code for call analytics data lake

add code samples for call insights

---

apps/amplify-demo/src/index.tsx

**Issue #:**
Update the import for Amplify
**Testing**

Update Amplify import

---

apps/chat/README.md
apps/chat/src/api/ChimeAPI.js
apps/chat/src/backend/serverless/template.yaml
apps/chat/src/containers/channels/ChannelsWrapper.jsx
apps/chat/src/containers/messages/Messages.css

**Issue #:**
Update to use regional SDKs for Chime SDK clients
**Testing**
Tested using the demo app and exercising the chat/meetings integration scenarios from Q&A.
Yes. By running the chat demo app.
npm run build was executed.

Update to regional SDKs

---

apps/meeting/package-lock.json
apps/meeting/package.json

**Issue #:**
Update the JS SDK version in the meeting demo and React Libary submodule.
**Testing**
npm run build

Update JS SDK version in Meeting demo and React Library Submodule

---

apps/chat/package-lock.json

**Issue #:**
- run "npm audit fix" to resolve audit issues and then sanity check the demo 
**Testing**
npm run start
npm run start  - sanity checks
yes

Update chat demo dependencies

---

apps/chat/package-lock.json

**Issue #:**
- Run npm audit fix to resolve audit findings, then did a sanity check on the demo
**Testing**
npm run start - sanity check

Update moderated chat demo dependencies

---

apps/meeting/package-lock.json
apps/meeting/package.json

**Issue #:**
* Install webpack@5.89.0
* run `npm audit fix`
**Testing**
Verified e2e flow in meeting demo.
meeting dmeo
`npm run build` succeeded.

Security patching

---

apps/moderated-chat-and-sentiment-analysis/package-lock.json

**Issue #:**
- "npm audit fix" and then sanity check the demo
**Testing**
'npm run build && npm run start'

Update moderated chat dependencies

---

utils/singlejs/package-lock.json

**Issue #:**
- Update Chime SDK dependency to 3.19.0 and npm audit fix
**Testing**
npm run build - confirm bundle is created

Update singlejs util

---

apps/meeting/src/components/DeviceSelection/CameraDevices/index.tsx

remove unused import

---

apps/meeting/src/containers/MeetingForm/index.tsx

This reverts commit 97e20aa8a869927486d32b003b56dcdb2ed5020d.
**Issue #:**
This change is not needed any more with React and JS fixes.
**Testing**

Revert "Avoid re-render upon text input change in join page (#443)"
