README.md
analytics/meeting-event-dashboard/README.md
analytics/meeting-event-dashboard/meeting-events-blog-template.yaml

**Issue #:**
- N?A
- Add the AWS CloudFormation template for the [Monitoring and troubleshooting with Amazon Chime SDK meeting events](https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/) blog post.
**Testing**
1. How did you test these changes? I deployed the stack in multiple regions and ensure that the dashboard shows data.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? No

Add the CF template for the meeting-event blog post

---

README.md
apps/iOS-WKWebView-sample/.gitignore
apps/iOS-WKWebView-sample/README.md
apps/iOS-WKWebView-sample/WkWebView Demo.xcodeproj/project.pbxproj
apps/iOS-WKWebView-sample/WkWebView Demo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
apps/iOS-WKWebView-sample/WkWebView Demo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
apps/iOS-WKWebView-sample/WkWebView Demo.xcodeproj/xcshareddata/xcschemes/WkWebView Demo.xcscheme
apps/iOS-WKWebView-sample/WkWebView Demo/AppConfiguration.swift
apps/iOS-WKWebView-sample/WkWebView Demo/AppDelegate.swift
apps/iOS-WKWebView-sample/WkWebView Demo/Assets.xcassets/AccentColor.colorset/Contents.json
apps/iOS-WKWebView-sample/WkWebView Demo/Assets.xcassets/AppIcon.appiconset/Contents.json
apps/iOS-WKWebView-sample/WkWebView Demo/Assets.xcassets/Contents.json
apps/iOS-WKWebView-sample/WkWebView Demo/Base.lproj/LaunchScreen.storyboard
apps/iOS-WKWebView-sample/WkWebView Demo/Base.lproj/Main.storyboard
apps/iOS-WKWebView-sample/WkWebView Demo/HomeViewController.swift
apps/iOS-WKWebView-sample/WkWebView Demo/Info.plist
apps/iOS-WKWebView-sample/WkWebView Demo/SceneDelegate.swift
apps/iOS-WKWebView-sample/WkWebView Demo/WkWebViewController.swift

Issue #:
Description of changes:
Adds a iOS WKWebView sample iOS application. The sample is a basic iOS application that opens a generic WKWebView from iOS WebKit. The builder must supply a WebRTC based meeting application url before building the application so that the WebView will load the meeting application. This application is built on iOS 14.4, but should work for 14.3+, since WKWebviews suport WebRTC after iOS 14.3.
This was reviewed and approved by two members of the mobile team.
Testing
Provided a meeting demo url, and then built the application. I ran on a simulator and on my own device. To run on my own device, I provided a personal developer account to sign the application before building.
How did you test these changes?
Join a Chime based meeting from within a wkwebview. …

Add iOS WKWebView Sample

---

apps/chat/package-lock.json
apps/moderated-chat-and-sentiment-analysis/package-lock.json

Update `dns-packet` and `browserslist` to `1.3.4` and `4.16.6`.
**Testing**
1. How did you test these changes? Manually ran the chat and moderated chat demo and verified that they rendered correctly.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes the chat and moderated chat demo.

[Chat] Bump dependencies version for multiple demos

---

apps/chat/package-lock.json

Bump `ws` dependency to version `6.2.2`
**Testing**
1. How did you test these changes? Ran the demo and verified the app was rendered correctly,
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes, the chat demo.

Bump ws dependency version for chat demo

---

apps/chat/src/containers/loginWithCredentialExchangeService/LoginWithCredentialExchangeService.jsx
apps/chat/src/views/Signin/index.jsx

Minor css update so that the auth option selection on the chat demo sign in screen is consistent with other fields.
**Testing**
1. How did you test these changes? Launched the app and verify that it was rendered correctly.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes, chat app.

[Chat] Minor css changes to the auth option in chat demo

---

apps/iOS-WKWebView-sample/WkWebView Demo.xcodeproj/project.pbxproj
apps/iOS-WKWebView-sample/WkWebView DemoUITests/Info.plist
apps/iOS-WKWebView-sample/WkWebView DemoUITests/WkWebView_DemoUITests.swift

**Issue #:**
Add XCUITest to the iOS WKWebView Demo. This test will be run as a Github Action test in the Chime SDK for Javascript repository. The test only works when there is a valid hosted Chime SDK meeting url in the AppConfiguration.swift file. The test will load the meeting url in the WKWebview and verify that the meeting can be joined. 
**Testing**
Ran the tests locally and verified the tests pass. 
The iOS WKWebview Demo is used.

Add XCUITest to iOS WKWebview Demo

---

apps/Android-WebView-sample/.gitignore
apps/Android-WebView-sample/README.md
apps/Android-WebView-sample/app/build.gradle
apps/Android-WebView-sample/app/src/androidTest/java/com/amazonaws/android_webview_sample/AndroidWebView_UITest.kt
apps/Android-WebView-sample/app/src/main/AndroidManifest.xml
apps/Android-WebView-sample/app/src/main/java/com/amazonaws/android_webview_sample/AppConfig.kt
apps/Android-WebView-sample/app/src/main/java/com/amazonaws/android_webview_sample/MainActivity.kt
apps/Android-WebView-sample/app/src/main/java/com/amazonaws/android_webview_sample/MainFragment.kt
apps/Android-WebView-sample/app/src/main/java/com/amazonaws/android_webview_sample/WebviewFragment.kt
apps/Android-WebView-sample/app/src/main/res/layout/activity_main.xml
apps/Android-WebView-sample/app/src/main/res/layout/content_main.xml
apps/Android-WebView-sample/app/src/main/res/layout/fragment_main.xml
apps/Android-WebView-sample/app/src/main/res/layout/fragment_webview.xml
apps/Android-WebView-sample/app/src/main/res/navigation/nav_graph.xml
apps/Android-WebView-sample/app/src/main/res/values/colors.xml
apps/Android-WebView-sample/app/src/main/res/values/strings.xml
apps/Android-WebView-sample/app/src/main/res/values/themes.xml
apps/Android-WebView-sample/app/src/main/res/xml/backup_descriptor.xml
apps/Android-WebView-sample/build.gradle
apps/Android-WebView-sample/gradle.properties
apps/Android-WebView-sample/gradle/wrapper/gradle-wrapper.properties
apps/Android-WebView-sample/gradlew
apps/Android-WebView-sample/gradlew.bat
apps/Android-WebView-sample/settings.gradle

**Issue #:**
Implement a demo showcasing the Chime SDK inside of Android WebView
Added the Android WebView sample demo that showcases how to run a WebRTC meeting demo inside of Android WebView
**Testing**
- Clone the AndroidWebView branch from https://github.com/aws/amazon-chime-sdk-js
- Build the sdk
- Build the browser demo
- Deploy the serverless demo and copy the given url for later
- Launch the newly added Android-Webview-sample folder in Android Studio 4.2.2
- In the AppConfig.kt file replace PLACEHOLDER with the url from the serverless demo
- Connect a physical android device that is in developer mode
- Launch the app on the physical device
- On the android device press the 'Go to WebView' button
- Fill in the fields on …

Added a Android WebView sample demo

---

apps/chat/src/providers/ChatMessagesProvider/index.jsx

**Issue #45 :**
**Testing**
Launch demo, send message with attachement, confirm shows in chat.
The chat demo

fixes aws-samples/amazon-chime-sdk#45: Show attachment when recieving message via WebSocket

---

apps/meeting/package.json
apps/meeting/webpack.config.dev.js
apps/meeting/webpack.config.js

Running in dev with inline-source-map makes the bundle size bigger than the Lambda limit so serverless demo would not be able to fetch the page.
Create a new dev webpack config to run with npm run start for debugging. npm run build will use the default - production mode to reduce the bundle size.
**Testing**
- Test both `npm run start` and `npm run build` and verify the bundle size.
- Do serverless deployment and verify that it loads
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes, meeting demo.

Split webpack to dev and prod to reduce the bundle size for serverless demo

---

apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/webpack.config.dev.js
apps/meeting/webpack.config.js

**Issue #:**
Currently when running in dev mode, we do not load the source map for component library which makes it hard for debugging.
Enable source map loader for react library in webpack.
The react library already contains source map file.
**Testing**
1. How did you test these changes? `npm run start` and verified that we could put break point in component library.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes, meeting demo.

Enable source map loader for meeting demo

---

apps/meeting/package.json

**Issue #:**
Running `webpack serve` does not use `webpack.config.dev.js`.
It only works when webpack is building the project. 
Update the node script to use the `webpack.config.dev.js` when running locally.
**Testing**
Yes, in both dev and prod mode, check the demo app and webpack work well .
React meeting demo

Update node script to enable webpack dev mode

---

apps/meeting/tsconfig.json
apps/meeting/typings/amazon-chime-sdk-component-library-react.d.ts

To solve TS7016: Could not find a declaration file for module amazon-chime-sdk-component-library-react error in GitHub actions.
**Issue #:**
- The react component library is failing webpack building while the deploy github action workflow runs.
- The error is:
```
TS7016: Could not find a declaration file for module 'amazon-chime-sdk-component-library-react'. '/home/runner/work/amazon-chime-sdk-component-library-react/amazon-chime-sdk-component-library-react/amazon-chime-sdk/apps/meeting/node_modules/amazon-chime-sdk-component-library-react/lib/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/amazon-chime-sdk-component-library-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'amazon-chime-sdk-component-library-react';`
```
- Failed …

Add react component library declaration

---

README.md

**Issue #:**
https://github.com/aws/amazon-chime-sdk-js/issues/1739
Fix broken link for Android WebView Sample in README.
**Testing**
1. How did you test these changes? Verified the link worked.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Just doc change.

Fix Android WebView Sample link in README

---

apps/meeting/src/components/DeviceSelection/CameraDevices/index.tsx

**Issue #:**
Fix a bug where the background blur checkbox was being shown even when background blur was disabled.
**Testing**
ran the test locally and verified the checkbox shows when bg blur is enabled, and doesnt show when disabled. 
From the meeting form, disable bg blur, join the meeting, validate that the checkbox is not mounted. 
From the meeting form, enabled bg blur, join the meeting, validate that the checkbox is mounted.
React meeting demo

Conditionally show the background blur checkbox depending on if background blur is enabled

---

CONTRIBUTING.md
apps/meeting/CONTRIBUTING.md
apps/meeting/README.MD

**Issue #:**
- Provide guidance on how to contribute to the meeting demo specifically.
- Add "CONTRIBUTING" guidelines specific to apps/meeting demo.
- This PR must go in the "main" branch as it is adding contributing guidelines. Rest all will go to "meeting-dev" branch as per these newly added guidelines.
**Testing**
Documentation update, but tested the steps mentioned in the documentation.
NA.

Add contributing guidelines for apps/meeting demo

---

apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/server.js
apps/meeting/webpack.config.dev.js
apps/meeting/webpack.config.js

**Issue #80 :**
* Update the `webpack.config.dev.js` to not use `InlineChunkHtmlPlugin` which cause the infinite reloading issue.
* Remove the logic of sending HTML page from `server.js`.
* webpack-dev-server now handles the rendering of HTML pages.
* `server.js` handles Chime API calls only.
* Add some missing trailing commas.
* Add boundary of `webpack-dev-server` proxy.
* Remove `source-map-loader` dependency from `package.json`, because we don't need it anymore.
**Testing**
* Run the demo locally, make some change, and confirm the live reload works well.
* Deploy the demo and confirm it works well.
Yes, …

Fix Webpack infinite reloading

---

apps/meeting/webpack.config.js

**Issue #:**
The `endMeetingForAll` button returns 404 error.
Add '/end' endpoint to webpack-dev-server proxy
**Testing**
Tested in meeting demo and confirmed the fix can work.
Yes, meeting demo

Add '/end' endpoint to webpack-dev-server proxy

---

apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/containers/Navigation/index.tsx
apps/meeting/src/meetingConfig.ts
apps/meeting/src/providers/AppStateProvider.tsx
apps/meeting/src/providers/VideoTileGridProvider/Utils.ts
apps/meeting/src/providers/VideoTileGridProvider/index.tsx
apps/meeting/src/providers/VideoTileGridProvider/state.tsx

- Allow to select simulcast uplink and priority-based downlink policies
- Disable the simulcast in non-Chrome browser and priority-based on Firefox.
- Fix the issue where selecting webAudio or background blur clear out the form.
**Testing**
- Join a meeting with 3 videos in Chrome with simulcast and priority-based downlink policies.
- Verify that simulcast is enabled 
- Verify that zoom in and out button only shown when priority-based downlink policy is enabled.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes, the meeting demo.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Allow to enable simulcast and priority video policies

---

apps/real-time-collaboration/.gitignore
apps/real-time-collaboration/package-lock.json
apps/real-time-collaboration/packages/y-chime-messaging/src/channel.ts
apps/real-time-collaboration/packages/y-chime-messaging/src/messagingProvider.ts

**Issue #:**
- Fix security vulnerabilities.
- Updated either using `npm audit fix` or `npm update`.
- Used `npm audit fix` as this is a demo and should not affect any dependency upgrade unlike consumed SDK libraries.
- `quill` cannot be updated yet as there is no direct fix available:
https://github.com/quilljs/quill/issues/3364
- Removed `js` extension from some files to fix below eslint errors appearing after running `npm run build`.
**Testing**
Followed README, created the CloudFormation template and tested the demo using `npm run start`. Works fine. Joined with 2 attendees and the two different pointers for both of them on text editor could be seen as expected.
2. Can these changes be tested using one of the demo …

[real-time-collaboration] security alerts fix

---

apps/meeting/.eslintrc.json

**Issue #:**
Deploy serverlessly the meeting demo if it is in the same folder as react library will cause this error as eslint tries to search for eslint config in ancestor directory.
```
ESLint: 8.7.0
ESLint couldn't determine the plugin "react" uniquely.
- /home/runner/work/amazon-chime-sdk-component-library-react/amazon-chime-sdk-component-library-react/amazon-chime-sdk/apps/meeting/node_modules/eslint-plugin-react/index.js (loaded in ".eslintrc.json")
- /home/runner/work/amazon-chime-sdk-component-library-react/amazon-chime-sdk-component-library-react/node_modules/eslint-plugin-react/index.js (loaded in "../../../.eslintrc.json")
```
Specify root property to stop this behavior.
**Testing**
1. How did you test these changes? Test locally with …

Specify root in eslint config

---

apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/providers/AppStateProvider.tsx

Add keepLastFrameWhenPaused in demo to test this PR https://github.com/aws/amazon-chime-sdk-component-library-react/pull/721
**Testing**
1. How did you test these changes? Verify that the meeting configuration  
1. Join a meeting with priority based policy and ``keepLastFrameWhenPaused` selected.
2.  Throttle the network and make sure that remote videos are paused with last frame.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes, meeting demo.

Add keepLastFrameWhenPaused in demo

---

apps/meeting/src/components/DeviceSelection/CameraDevices/VideoTransformDropdown.tsx

**Issue #:**
Video input source can be changed by other components in the preview level which causes VideoTransformDropdown component to be out of sync.
Reset currently selected transform option in VideoTransformDropdown to `None` with useEffect if video input source was changed by other component.
**Testing**
QA verified that this issue is fixed.
Yes, meeting.

Reset VideoTransformDropdown selected transform if video source change

---

.gitmodules
apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/scripts/setup-chime-react-submodule.js

Add `amazon-chime-sdk-component-library-react` submodule so that the [meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting), which is often used to test development changes in `amazon-chime-sdk-component-library-react`, can use the latest changes from the library repo without waiting for npm release.
**Testing**
1. How did you test these changes? Manually run npm command.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? No

Add amazon-chime-sdk-component-library-react submodule

---

apps/meeting/src/containers/LocalMediaStreamMetrics/index.tsx
apps/meeting/src/containers/VideoStreamMetrics/index.tsx

**Issue #:**
Some metrics returned by `useMediaStreamMetrics` hook and `useBandwidthMetrics` hook are deprecated, need to remove them from meeting demo.
Removed any components that use `videoUpstreamGoogFrameHeight`, `videoUpstreamGoogFrameWidth`, `videoDownstreamGoogFrameHeight` and `videoDownstreamGoogFrameWidth`.
**Testing**
Run meeting demo and manually confirm it works as expected.
Yes, meeting demo.

Update the meeting demo to adopt to metrics changes

---

apps/meeting/package-lock.json
apps/meeting/src/containers/MeetingDetails/index.tsx
apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/utils/api.ts

- Fix the issue where the hosted region is blank due to the `mediaRegion` is removed from `MeetingManager`.
- Update the submodule commit.
**Testing**
1. How did you test these changes? Manually verified that media region is displayed in the meeting.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes meeting demo

Fix hosted region display

---

apps/meeting/src/app.tsx
apps/meeting/src/containers/Chat/ChatInput.tsx
apps/meeting/src/containers/Chat/Messages.tsx
apps/meeting/src/containers/Chat/Styled.tsx
apps/meeting/src/containers/Chat/index.tsx
apps/meeting/src/containers/Navigation/NavigationControl.tsx
apps/meeting/src/containers/Navigation/index.tsx
apps/meeting/src/providers/DataMessagesProvider/index.tsx
apps/meeting/src/providers/DataMessagesProvider/state.tsx
apps/meeting/src/providers/NavigationProvider.tsx
apps/meeting/src/theme/demoTheme.ts
apps/meeting/src/views/Meeting/Styled.ts
apps/meeting/src/views/Meeting/index.tsx

**Issue #:**
- Add DataMessagesProvider to manage the state of messages.
- Add a Messages component to use the messages from DataMessagesProvider
and show to UI.
- Add demo based light and dark theme to accomodate theme for Chat components.
This theme is extension of existing component library's themes + chat specific
theme.
- Adjust Navigation components to support Chat components with responsive UI
similar to Roster component.
**Testing**
- Test manually joining same meeting with different attendees.
- Checked for error or warning in console logs.
- Checked message sending and receiving works as expected.
- Tested responsive UI, check screenshots.
2. Can these changes be tested using one of the demo application? If yes, …

Add chat components based on DataMessages

---

apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/scripts/setup-chime-react-submodule.js
apps/meeting/serverless/src/handlers.js
apps/meeting/serverless/src/package-lock.json
apps/meeting/src/app.tsx
apps/meeting/src/components/MeetingControls/VideoInputTransformControl.tsx
apps/meeting/src/containers/DevicePermissionPrompt.tsx
apps/meeting/src/containers/EndMeetingControl/index.tsx
apps/meeting/src/containers/MeetingEventObserver/index.tsx
apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/hooks/useMeetingEndRedirect.tsx
apps/meeting/src/meetingConfig.ts
apps/meeting/src/providers/AppStateProvider.tsx
apps/meeting/src/types/index.ts
apps/meeting/webpack.config.js

**Issue #:**
- Necessary changes to use logger from component library.
- Component library PR: https://github.com/aws/amazon-chime-sdk-component-library-react/pull/772
**Testing**
- Deployed it and checked whether we get console logs as well as logs in AWS CloudWatch in the deployed account.
- If `LoggerProvider` is not mounted, only console logger will work as it is provided by default.
- apps/meeting

Use logger from component library

---

.gitmodules

**Issue #:** N/A
Currently, `npm install` will fail in forked repository by the following errors:
```
$ git clone https://github.com/simukappu/amazon-chime-sdk.git
$ cd amazon-chime-sdk/apps/meeting
$ npm install
> chime-sdk-meeting-demo@0.1.0 preinstall
> scripts/setup-chime-react-submodule.js
Setup amazon-chime-sdk-component-library-react submodule
,,Submodule 'amazon-chime-sdk-component-library-react' (git@github.com:aws/amazon-chime-sdk-component-library-react.git) registered for path './'
,,Cloning into '<working directory>/amazon-chime-sdk/amazon-chime-sdk-component-library-react'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists. …
```

Update submodule repository url from SSH to HTTPS

---

apps/chat/src/providers/AuthProvider.jsx

**Issue #:**
AWS Credentials did not implement refresh behavior and thus all APIs stopped working after they expire (1 hour).   
This change implements refresh behavior for AWS credentials used by Chime Messaging SDK
**Testing**
Run the demo for 1 hour both in Cognito signed in user and anonymous user.  For Cognito they refresh, for anonymous throw an console.error saying you need to implement it.  This is because for demo purposes the credential exchange service just gives back a 1 time token to auth, in real use cases it would validate a JWT or something and that could be used to get new credentials.
Yes …

Chat demo refreshes credentials when expire

---

apps/televisit-demo/backend/template.yaml
apps/televisit-demo/frontend/template.yaml

**Issue #:**
In order to resolve an app sec finding.
Enable s3 bucket versioning for televisit demo
**Testing**
needs to be deployed
n/a
yes

Enable s3 bucket versioning for televisit demo

---

apps/amplify-demo/.gitignore
apps/amplify-demo/lambda/index.js
apps/amplify-demo/package-lock.json
apps/amplify-demo/package.json
apps/amplify-demo/src/components/MeetingForm.tsx

**Issue #:**
1. Migrate amplify demo to v3 following migration guide.
2. Remove unused dependencies:
```
@testing-library/jest-dom
@testing-library/react
@testing-library/user-event
@types/jest
@types/node
```
3. Remove `amazon-chime-sdk-js` because it's already the peer dependency of `amazon-chime-sdk-component-library-react`.
4. Update following dependencies to latest version:
```
amazon-chime-sdk-component-library-react
aws-amplify
typescript
styled-components
react-scripts
```
5. Reduce security alarms from 22 to 15 by running `npm audit fix`.
6. Format the code in `apps/amplify-demo/lambda/index.js`.
**Testing**
Deploy the backend resources using amplify following the readme. Run the deme locally and try a e2e testing. …

Migrate amplify-demo to use React Component Library v3

---

apps/chat/src/backend/serverless/template.yaml

**Issue #:**
Prevent creating user/none in chat demo.  There lack of a return was resulting in a user/none being created that is never used
**Testing**
Ran app and created new user and logged in.

Prevent creating user/none in chat demo

---

apps/chat/package.json
apps/chat/src/backend/serverless/template.yaml

**Issue #:** related : https://github.com/aws-samples/amazon-chime-sdk/issues/224
- fix user auth issue caused by blank app config params. 
- disable cloudfront cache to support dynamic assets
**Testing**
- Run `npm run deploy`
- Create users and attempt to login. login should succeed and no cognito/auth errors due to blank user pool ids should be seen.
4. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? yes, chat demo app.
5. If applicable, have you run `npm run build` successfully locally to fix all warnings and errors? yes
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

fix user auth flow bug; disable cloudfront cache to support dynamic assets

---

apps/chat/src/Config.js

**Issue #:224**
**Description of changes: The s3 attachments bucket property was incorrectly referenced.**
**Testing**
- Ran the build steps and confirmed attachments are now working out of the box.
- Yes, using the chat demo application
- N/A

Fix for s3 bucket name for chat demo when using attachments

---

apps/chat/README.md
apps/chat/package.json
apps/chat/src/backend/serverless/template.yaml

Restrict CORS to cloudfront and localhost origins; upgrade nodejs to 14.x
**Issue #:** 
https://github.com/aws-samples/amazon-chime-sdk/issues/224
Restrict CORS to CloudFront and localhost origins; 
- This addresses the sign in with credential exchange service issue mentioned in https://github.com/aws-samples/amazon-chime-sdk/issues/224
Upgrade nodejs to 14.x for the lambdas
- this is to match the min required nodejs version (which is 14.x) described in the readme.
- also the new preflight request lambda code requires `nodejs 14.x`
Update ReadMe accordingly
**Testing**
Tested the chat demo app with the following steps:
- Run `npm run deploy` to deploy the demo app backend and frontend resources
- Open the CloudFront endpoint …

Restrict CORS to cloudfront and localhost origins; upgrade nodejs to 14.x

---

apps/meeting/src/containers/MeetingJoinDetails.tsx
apps/meeting/src/containers/SIPMeeting/index.tsx

**Issue #:**
When running `tsc` to compile typescript, there're errors regarding the type of `error` in `catch` block.
* Cast the `error` to `Error` in `try catch` block
**Testing**
Run `tsc` and confirm there's no error after change.
Make sure meeting demo works after change.
2. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes, meeting demo.
Yes

Fix type error when running tsc in meeting demo

---

apps/alexa-skill-calling/skill-sample-simple-customer-support/README.md
apps/alexa-skill-calling/skill-sample-simple-customer-support/simple-customer-support-skill/interactionModels/custom/en-US.json
apps/alexa-skill-calling/skill-sample-simple-customer-support/simple-customer-support-skill/lambda/config.js
apps/alexa-skill-calling/skill-sample-simple-customer-support/simple-customer-support-skill/lambda/index.js
apps/alexa-skill-calling/skill-sample-simple-customer-support/simple-customer-support-skill/lambda/local-debugger.js
apps/alexa-skill-calling/skill-sample-simple-customer-support/simple-customer-support-skill/lambda/package.json
apps/alexa-skill-calling/skill-sample-simple-customer-support/simple-customer-support-skill/lambda/util.js
apps/alexa-skill-calling/skill-sample-simple-customer-support/simple-play-audio/index.js

**Issue #:**
None. This is a new feature.
Amazon Chime SDK Alexa skill calling allows enterprise customers to enable calling directly in their Amazon Alexa Skills. In this demo skill, we build an Alexa skill that allows a customer to place a call to a customer support.
**Testing**
Deploy this Alexa skill using Alexa Developer Console and deploy this SMA into Amazon Chime SDK PSTN Audio. Use this Alexa skill to call into the SMA.
This change is not part of the demo application
Tested within a Lambda in Alexa …

Add Alexa skill calling sample skill

---

utils/singlejs/package-lock.json
utils/singlejs/package.json
utils/singlejs/rollup.config.js

**Issue #:**
SingleJS is using 2.0 JS SDK, and current setup fails if using 3.7+
- Add json loader
- Change mainfields to fix issue with aws-sdk grabbing the wrong file
**Testing**
npm run bundle
No
N/A

Update singlejs to latest version of rollup and chime js sdk

---

apps/meeting/CONTRIBUTING.md
apps/meeting/README.MD
apps/meeting/package-lock.json
apps/meeting/src/containers/MeetingStatusNotifier/index.tsx
apps/meeting/src/views/Meeting/index.tsx

This will help in testing various meeting statuses from Amazon Chime SDK component library for React.
**Issue #:**
- Add a new component `MeetingStatusNotifier` to throw UI notifications based on meeting status updates from underlying Amazon Chime SDK component library for React.
- Update `amazon-chime-sdk-component-library-react` submodule which includes the new `MeetingStatus.Reconnecting` status.
**Testing**
1. Run the demo app.
2. Verify correct connecting and connected statuses are shown in meeting screen.
3. Turn internet off and verify reconnecting status is notified.
4. Keep the internet off and see reconnecting statues comes up until the internet is connected back.
5. Once internet is connected back verify meeting …

Add meeting status notifier to React component lib meeting demo

---

utils/singlejs/README.md
utils/singlejs/package-lock.json
utils/singlejs/package.json
utils/singlejs/src/index.js

**Issue #:**
#243 
To fix rollup bundling post JS SDK 3.7.0, we added `type: "module"` to package.json. This made the singles to be an ES6 module and hence it required the export from `src/index.js` to change accordingly.
**Testing**
- Created and opened `index.html` like below and check in console, logger is loaded and logs some statements.
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
<script src="build/amazon-chime-sdk.min.js"></script>
<script>
const logger = new ChimeSDK.ConsoleLogger('ChimeMeetingLogs', ChimeSDK.LogLevel.INFO);
const deviceController = …
```

Add default export to make bundled ES6 module work

---

utils/singlejs/package-lock.json
utils/singlejs/package.json
utils/singlejs/rollup.config.js

**Issue #:**
#299 
- Replace the deprecated terser plugin to current maintained one.
**Testing**
Create below test.html and verify the Chime JS SDK logger logs device controller logs.
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
<script src="build/amazon-chime-sdk.min.js"></script>
<script>
const logger = new ChimeSDK.ConsoleLogger('ChimeMeetingLogs', ChimeSDK.LogLevel.INFO);
const deviceController = new ChimeSDK.DefaultDeviceController(logger);
</script>
</head>
<body>
</body>
</html>
```
2. Can these changes be tested using one of the demo application? If …

Replace terser rollup plugin to fix npm install issue

---

apps/chat/src/containers/input/Input.jsx
apps/televisit-demo/frontend/src/containers/input/Input.jsx

**Issue #:** 306
**Description of changes:** 
Fix attachment bug in chat and televisit demo app when user sends a message with attachment. The bug is, when sending a message with an attachment, after user selects the attachment, if user click on the "x" to cancel/de-select the attachment, the current bug will send the attachment instead. This code change fixes the behavior to allow user to de-select or cancel the attachment.
**Testing** 
Run the demo app locally and verified that the issue is fixed.
3. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? Yes the chat demo application can be used to test it.
4. If applicable, have you run `npm run build` successfully locally to fix all …

Fix attachment bug when cancel the attachment selection

---

apps/alexa-skill-calling/skill-sample-simple-customer-support/simple-customer-support-skill/lambda/index.js

**Issue #:**
N/A
Leave the output speech field blank. Alexa Skill Calling now natively announce an Alexa Skill call is starting. The native Amazon announcement will play even if the sample skill provide a sample announcement. Alexa Skill builder add to the native call announcement by providing call announcement phrase in output speech field.
**Testing**
Tested Alexa Skill with Alexa device.
Tested Alexa Skill with Alexa device.
No. This change must be tested with an Alexa device.
Completed
By submitting this …

Update sample skill call announcement

---

apps/meeting/package-lock.json
apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/providers/AppStateProvider.tsx

**Issue #:**
When one use `skipDeviceSelection` while joining a meeting, then, the user will have to manually select the devices either in device setup view or in meeting view screen.
**Testing**
- Load the meeting demo
- Put in meeting and attendee details
- Check "Skip device selection" option
- Verify that the "Device setup" view shows next.
- Select or change the devices manually to select the audio and video devices and then join the meeting.
- Verify in meeting the attendee is seen in roster and can start video and sees it, also the mic indicator is active when talked.
- Do the same steps without checking "Skip default meeting join device listing and selection" option to make sure both enabling/disabling "Skip default …

Add `skipDeviceSelection` flag in meeting join view

---

apps/meeting/package-lock.json
apps/meeting/package.json

**Issue #:**
N/A
- Upgrade the Chime SDK React Component Library (submodule) to the latest commit with the React 18 support.
**Testing**
- Ran the build script.
- Yes, `apps/meeting`
- Yes.

Upgrade the Chime SDK React Component Library submodule

---

apps/chat/src/backend/serverless/channelFlowBlogTemplate.yaml
apps/chat/src/backend/serverless/template.yaml
apps/moderated-chat-and-sentiment-analysis/backend/template.yaml
apps/real-time-collaboration/backend/template.yaml

**Issue #:**
Upgrade NodeJS from 12 to 14 to fix Cloudformation deployment failure
**Testing**
1. How did you test these changes? For chat demo with main template and channel flow template, as well as the real time collaboration demo and post processing demo, I deployed the new template to Cloudformation and deployment succeeded. Used the output from the deployment and started the local server, everything works as expected, such as user sign up, log in, createChannel and enable channel flow, then send messages.
3. Can these changes be tested using one of the demo application? If yes, which demo application can be used to test it? The chat demo applications,
4. If applicable, have you run `npm run build` successfully locally to fix all warnings and errors? Yes. …

Upgrade NodeJS from 12 to 14 to fix Cloudformation deployment failure

---

apps/televisit-demo/backend/template.yaml

**Issue #:**
N/A
- Upgrade the Node version from 12 to 18 for the AWS Lambda functions within the televisit-demo.
- Remove the `AccessControl: LogDeliveryWrite` from the `LoggingBucket` in the televisit-demo. The deployment is unsuccessful because of the `AccessControl: LogDeliveryWrite`.
**Testing**
Deployed the demo
Yes, the `televisit-demo`
N/A

Update the Node from 12 to 18 in the televisit-demo

---

apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/server.js
apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/providers/SIPMeetingProvider/SIPMeetingManager.ts
apps/meeting/src/utils/api.ts

**Issue #:**
Migrate aws sdk to v3 and refactor server to use express in react meeting demo.
1. Migrate aws sdk from v2 to v3
2. Update server to node express server
**Testing**
Test the meeting demo in e2e flow. Will have a separate CR to update serverless demo.
Yes, React meeting demo
`npm run build` succeeded.

Update meeting demo server to use aws sdk v3 and express

---

apps/meeting/.eslintrc.json
apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/server.js
apps/meeting/serverless/src/handlers.js
apps/meeting/serverless/src/package-lock.json
apps/meeting/serverless/src/package.json
apps/meeting/serverless/template.yaml
apps/meeting/src/constants/routes.ts
apps/meeting/src/containers/EndMeetingControl/index.tsx
apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/containers/MeetingJoinDetails.tsx
apps/meeting/src/containers/MeetingProviderWrapper/index.tsx
apps/meeting/src/containers/MeetingStatusNotifier/index.tsx
apps/meeting/src/containers/NoMeetingRedirect.tsx
apps/meeting/src/hooks/useMeetingEndRedirect.tsx
apps/meeting/src/views/Home/index.tsx

**Issue #:**
* Migrate aws sdk from v2 to v3 for serverless handler
* Migrate react router from v5 to v6 to be compatible with react 18
* 
**Testing**
Deploy the serverless demo and tested e2e.
Yes react meeting demo, deploy serverless demo and test e2e.
`npm run build` succeeded.

Migrate aws sdk to v3 for serverless demo and react router to v6

---

apps/meeting/src/components/DeviceSelection/CameraDevices/BackgroundReplacementDropdown.tsx
apps/meeting/src/components/DeviceSelection/CameraDevices/index.tsx

**Issue #:**
https://sim.amazon.com/issues/WTBugs-30848
Move the usage of useBackgroundReplacement into BackgroundReplacementProvider
**Testing**
Test with demo app
Yes, apps/meeting
Yes

Fix error useBackgroundReplacement not in BackgroundReplacementProvider

---

apps/meeting/package-lock.json

**Issue #:**
The current React SDK version used in meeting demo does not contain the new APIs for replacement.
Bump submodule version to latest.
**Testing**
Run the demo and verified locally.
Meeting demo. E2e test and verify `background replacement - beach` option is working fine.
Yes

Bump submodule version to latest

---

apps/meeting/src/containers/MeetingProviderWrapper/index.tsx

**Issue #:**
Pass logger to bgBlur, bgReplacement processors so the logging behavior is consistent with rest of components
**Testing**
1. How did you test these changes? Setting log level to off, verify the log doesn't show on console.

Pass logger to bgBlur, bgReplacement processors

---

apps/meeting/package-lock.json
apps/meeting/package.json

**Issue #:**
There's type error in meeting demo. Because the meeting app is using `amazon-chime-sdk-js@3.21.1`, the default submodule commit is using `v3.23.0`.
Update JS SDK version in meeting demo to match submodule v3.23.0
**Testing**
Run demo locally and verify no type error.
N/A
N/A

Update JS SDK version in meeting demo to match submodule

---

apps/meeting/src/containers/MeetingForm/index.tsx

**Issue #: every key stroke will initiate a page re-render.
**Testing**
Locally and deployed to personal CF

Avoid re-render the page upon text input change

---

apps/meeting/package-lock.json
apps/meeting/package.json
apps/meeting/src/containers/DynamicMeetingControls/Styled.ts
apps/meeting/src/containers/DynamicMeetingControls/index.tsx
apps/meeting/src/containers/MeetingControls/Styled.ts
apps/meeting/src/containers/MeetingControls/index.tsx
apps/meeting/src/containers/MeetingStatusNotifier/index.tsx
apps/meeting/src/views/Meeting/Styled.ts
apps/meeting/src/views/Meeting/index.tsx

**Issue #:**
- Update submodule to latest main line that contains styled-components v6 update.
- Migrate meeting demo to use styled-components v6
- 
**Testing**
Run the meeting demo, verified e2e flow, no build error and ui.
Yes, meeting demo. Run the demo, verified e2e flow, no build error and ui.
Yes, passed

Upgrade styled-components to v6 in meeting demo

---

apps/meeting/package-lock.json
apps/meeting/server.js
apps/meeting/src/components/VideoTileGrid/Styled.tsx
apps/meeting/src/components/VideoTileGrid/VideoTileGrid.tsx
apps/meeting/src/containers/MeetingForm/index.tsx
apps/meeting/src/containers/MeetingProviderWrapper/index.tsx
apps/meeting/src/providers/AppStateProvider.tsx
apps/meeting/src/views/Meeting/index.tsx

**Issue #:**
- Add multiple content shares support in meeting demo
- Create a local VideoTileGrid to display 2 content share tiles
- Add a check box to meeting form to enable concurrent content shares
**Testing**
- Tested e2e locally.
yes, meeting demo
yes

Add multiple content shares support in meeting demo
